RDK-35329: animated splash screen support with APNG
rdkcentral/RDKShell pull request #124
Opened 2022-04-25 13:20 UTC by madanagopalt

2022-04-25 14:22 UTC, mhughesacn commented
Hi madangolapt: The scan is complaining because there are good matches to pxCore.  If you have another original source in the two files below, please tell me.  Otherwise, you need to credit pxCore as follows:

1.
Code match in rdkshellimage.cpp, please insert the following before Line 704 (BlendOver,loadAPng)

```
Based on pxCore, Copyright 2005-2018 John Robinson
Licensed under the Apache License, Version 2.0
```

2.
Code match in apngutils.cpp, please insert before line 173 (blit):

```
pxCore Copyright 2005-2018 John Robinson
Licensed under the Apache License, Version 2.0

```
3.
In NOTICE, please append:

```
pxCore Copyright 2005-2018 John Robinson
Licensed under the Apache License, Version 2.0

```

Thank you - Martin Hughes, RDK CMF Compliance Team

2022-05-02 19:26 UTC, mfiess requested changes
Please make the requested changes.

2022-05-05 18:21 UTC, mfiess requested changes

2022-05-05 18:21 UTC, mfiess commented on rdkshellimage.cpp
> +    void Image::BlendOver(unsigned char **rows_destination, unsigned char **rows_source, unsigned int x, unsigned int y, unsigned int width, unsigned int height)
Please ensure the method names are camel case starting with a lower case letter to keep consistency with the other RDKShell APIs.

2022-05-05 18:21 UTC, mfiess commented on rdkshellimage.h
> +            void BlendOver(unsigned char **rows_destination, unsigned char **rows_source, unsigned int x, unsigned int y, unsigned int width, unsigned int height);
Please ensure the method names are camel case starting with a lower case letter to keep consistency with the other RDKShell APIs.

2022-08-17 04:15 UTC, closed without merging